### ISSUE TITLE
Error on extending from PassportStrategy

### ISSUE THREAD

**Issue by leosuncin** [Kamil-Kalandarov/kupipodariday-backend#1]
You need to pass a string to `PassportStrategy`

https://github.com/Kamil-Kalandarov/kupipodariday-backend/blob/d1dba777c4f2584674033d9621be9f99c33d0061/src/auth/strategies/jwt.strategy.ts#L8

Change it to

```ts
export class JwtStartegy extends PassportStrategy(Startegy, 'jwt') {
```

The same goes for

https://github.com/Kamil-Kalandarov/kupipodariday-backend/blob/d1dba777c4f2584674033d9621be9f99c33d0061/src/auth/strategies/local.strategy.ts#L9

Change it to

```ts
export class LocalStrategy extends PassportStrategy(Startegy, 'local') {
```

Edit: pass the string as a second parameter

**Comment by leosuncin** [comment]
Also, define the `validate` method in the JWT strategy

https://github.com/Kamil-Kalandarov/kupipodariday-backend/blob/d1dba777c4f2584674033d9621be9f99c33d0061/src/auth/strategies/jwt.strategy.ts#L8-L16

**Comment by Kamil-Kalandarov** [comment]
no, i pass a Strategy from passport-jwt at JwtStartegy and Strategy from local-strategy
